USED ORACLE LIVE SQL: https://livesql.oracle.com/

CREATE VIEW FLOORS_OF_POSITIVE_TESTED_EMPLOYEES AS SELECT EMP_ID, FLOOR_NUMB FROM Employee WHERE EMP_ID IN (SELECT EMP_ID FROM Tests WHERE TEST_RESULT = 'positive');

SELECT * FROM FLOORS_OF_POSITIVE_TESTED_EMPLOYEES;

SELECT FLOOR_NUMB, COUNT(FLOOR_NUMB) AS "NUMB_OF_PEOPLE_TESTED_POSITIVE_FROM_THIS_FLOOR" FROM FLOORS_OF_POSITIVE_TESTED_EMPLOYEES GROUP BY FLOOR_NUMB ORDER BY NUMB_OF_PEOPLE_TESTED_POSITIVE_FROM_THIS_FLOOR DESC FETCH NEXT 1 ROWS ONLY;