USED ORACLE LIVE SQL: https://livesql.oracle.com/

SELECT COUNT(*) AS "NUMBER_OF_SCANS_IN_JAN" FROM Scans WHERE SCAN_DATE BETWEEN '01-JAN-21' AND '31-JAN-21';

SELECT COUNT(*) AS "NUMBER_OF_TESTS_IN_JAN" FROM Tests WHERE TEST_DATE BETWEEN '01-JAN-21' AND '31-JAN-21';

SELECT COUNT(*) AS "NUMBER_OF_SYMPTOMS_REPORTED_IN_JAN" FROM Symptom WHERE DATE_REPORTED BETWEEN '01-JAN-21' AND '31-JAN-21';

SELECT COUNT(*) AS "NUMBER_OF_POSITIVE_CASES_IN_JAN" FROM Tests WHERE TEST_RESULT = 'positive' AND TEST_DATE BETWEEN '01-JAN-21' AND '31-JAN-21';